def get_data_from_airports():
    return [
            {'id': 0, 'estado': 'Aguascalientes', 'ciudad': 'Aguascalientes', 'nombre_recinto': 'Aeropuerto Internacional Lic. Jesus Teran Peredo (AGU)', 'latitud': '21.7056', 'longitud': '-102.3178'},
            {'id': 1, 'estado': 'Baja California', 'ciudad': 'Tijuana', 'nombre_recinto': 'Aeropuerto Internacional de Tijuana (TIJ)', 'latitud': '32.5411', 'longitud': '-116.9702'},
            {'id': 2, 'estado': 'Baja California Sur', 'ciudad': 'San Jose del Cabo', 'nombre_recinto': 'Aeropuerto Internacional de Los Cabos (SJD)', 'latitud': '23.1518', 'longitud': '-109.721'},
            {'id': 3, 'estado': 'Campeche', 'ciudad': 'Campeche', 'nombre_recinto': 'Aeropuerto Internacional de Campeche (CPE)', 'latitud': '19.8167', 'longitud': '-90.5003'},
            {'id': 4, 'estado': 'Chiapas', 'ciudad': 'Tuxtla Gutierrez', 'nombre_recinto': 'Aeropuerto Internacional Angel Albino Corzo (TGZ)', 'latitud': '16.563', 'longitud': '-93.0267'},
            {'id': 5, 'estado': 'Chihuahua', 'ciudad': 'Chihuahua', 'nombre_recinto': 'Aeropuerto Internacional General Roberto Fierro Villalobos (CUU)', 'latitud': '28.702', 'longitud': '-105.964'},
            {'id': 6, 'estado': 'Ciudad de Mexico', 'ciudad': 'Ciudad de Mexico', 'nombre_recinto': 'Aeropuerto Internacional Benito Juarez (MEX)', 'latitud': '19.4361', 'longitud': '-99.0719'},
            {'id': 7, 'estado': 'Coahuila', 'ciudad': 'Saltillo', 'nombre_recinto': 'Aeropuerto Internacional Plan de Guadalupe (SLW)', 'latitud': '25.5495', 'longitud': '-100.9297'},
            {'id': 8, 'estado': 'Colima', 'ciudad': 'Colima', 'nombre_recinto': 'Aeropuerto Nacional Licenciado Miguel de la Madrid (CLQ)', 'latitud': '19.277', 'longitud': '-103.577'},
            {'id': 9, 'estado': 'Durango', 'ciudad': 'Durango', 'nombre_recinto': 'Aeropuerto Internacional General Guadalupe Victoria (DGO)', 'latitud': '24.1242', 'longitud': '-104.528'},
            {'id': 10, 'estado': 'Guanajuato', 'ciudad': 'Silao', 'nombre_recinto': 'Aeropuerto Internacional de Guanajuato (BJX)', 'latitud': '20.9935', 'longitud': '-101.48'},
            {'id': 11, 'estado': 'Guerrero', 'ciudad': 'Acapulco', 'nombre_recinto': 'Aeropuerto Internacional General Juan N. Alvarez (ACA)', 'latitud': '16.7571', 'longitud': '-99.7537'},
            {'id': 12, 'estado': 'Hidalgo', 'ciudad': 'Pachuca', 'nombre_recinto': 'Aeropuerto Nacional de Pachuca (PCA)', 'latitud': '20.0939', 'longitud': '-98.7827'},
            {'id': 13, 'estado': 'Jalisco', 'ciudad': 'Guadalajara', 'nombre_recinto': 'Aeropuerto Internacional Miguel Hidalgo y Costilla (GDL)', 'latitud': '20.5218', 'longitud': '-103.3112'},
            {'id': 14, 'estado': 'Estado de Mexico', 'ciudad': 'Toluca', 'nombre_recinto': 'Aeropuerto Internacional Lic. Adolfo Lopez Mateos (TLC)', 'latitud': '19.3371', 'longitud': '-99.566'},
            {'id': 15, 'estado': 'Michoacan', 'ciudad': 'Morelia', 'nombre_recinto': 'Aeropuerto Internacional General Francisco J. Mugica (MLM)', 'latitud': '19.8501', 'longitud': '-101.025'},
            {'id': 16, 'estado': 'Morelos', 'ciudad': 'Cuernavaca', 'nombre_recinto': 'Aeropuerto Internacional General Mariano Matamoros (CVJ)', 'latitud': '18.8347', 'longitud': '-99.2613'},
            {'id': 17, 'estado': 'Nayarit', 'ciudad': 'Tepic', 'nombre_recinto': 'Aeropuerto Nacional Amado Nervo (TPQ)', 'latitud': '21.4195', 'longitud': '-104.8421'},
            {'id': 18, 'estado': 'Nuevo Leon', 'ciudad': 'Monterrey', 'nombre_recinto': 'Aeropuerto Internacional General Mariano Escobedo (MTY)', 'latitud': '25.7785', 'longitud': '-100.1071'},
            {'id': 19, 'estado': 'Oaxaca', 'ciudad': 'Oaxaca', 'nombre_recinto': 'Aeropuerto Internacional Xoxocotlan (OAX)', 'latitud': '16.9999', 'longitud': '-96.7266'},
            {'id': 20, 'estado': 'Puebla', 'ciudad': 'Huejotzingo', 'nombre_recinto': 'Aeropuerto Internacional Hermanos Serdan (PBC)', 'latitud': '19.1581', 'longitud': '-98.3714'},
            {'id': 21, 'estado': 'Queretaro', 'ciudad': 'Queretaro', 'nombre_recinto': 'Aeropuerto Intercontinental de Queretaro (QRO)', 'latitud': '20.6173', 'longitud': '-100.1867'},
            {'id': 22, 'estado': 'Quintana Roo', 'ciudad': 'Cancun', 'nombre_recinto': 'Aeropuerto Internacional de Cancun (CUN)', 'latitud': '21.0365', 'longitud': '-86.877'},
            {'id': 23, 'estado': 'San Luis Potosi', 'ciudad': 'San Luis Potosi', 'nombre_recinto': 'Aeropuerto Internacional Ponciano Arriaga (SLP)', 'latitud': '22.2555', 'longitud': '-100.93'},
            {'id': 24, 'estado': 'Sinaloa', 'ciudad': 'Culiacan', 'nombre_recinto': 'Aeropuerto Internacional de Culiacan (CUL)', 'latitud': '24.7645', 'longitud': '-107.4743'},
            {'id': 25, 'estado': 'Sonora', 'ciudad': 'Hermosillo', 'nombre_recinto': 'Aeropuerto Internacional General Ignacio Pesqueira Garcia (HMO)', 'latitud': '29.0959', 'longitud': '-111.0489'},
            {'id': 26, 'estado': 'Tabasco', 'ciudad': 'Villahermosa', 'nombre_recinto': 'Aeropuerto Internacional Carlos Rovirosa Perez (VSA)', 'latitud': '17.9967', 'longitud': '-92.8174'},
            {'id': 27, 'estado': 'Tamaulipas', 'ciudad': 'Tampico', 'nombre_recinto': 'Aeropuerto Internacional General Francisco Javier Mina (TAM)', 'latitud': '22.2964', 'longitud': '-97.8659'},
            {'id': 28, 'estado': 'Tlaxcala', 'ciudad': 'Tlaxcala', 'nombre_recinto': 'Aeropuerto Nacional de Tlaxcala (TXA)', 'latitud': '19.4153', 'longitud': '-98.1112'},
            {'id': 29, 'estado': 'Veracruz', 'ciudad': 'Veracruz', 'nombre_recinto': 'Aeropuerto Internacional General Heriberto Jara (VER)', 'latitud': '19.1448', 'longitud': '-96.1873'},
            {'id': 30, 'estado': 'Yucatan', 'ciudad': 'Merida', 'nombre_recinto': 'Aeropuerto Internacional Manuel Crescencio Rejon (MID)', 'latitud': '20.937', 'longitud': '-89.6577'},
            {'id': 31, 'estado': 'Zacatecas', 'ciudad': 'Calera de Victor Rosales', 'nombre_recinto': 'Aeropuerto Internacional General Leobardo C. Ruiz (ZCL)', 'latitud': '22.8972', 'longitud': '-102.686'},
        ]